name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-8-jdk python3 python3-pip
        python3 -m pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK and NDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
        unzip commandlinetools-linux-6609375_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-29" "build-tools;29.0.3" "ndk;21.3.6528147"
      env:
        ANDROID_HOME: $HOME/android-sdk

    - name: Build APK
      run: |
        buildozer android debug
      env:
        ANDROID_HOME: $HOME/android-sdk
